from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

_KIND_ALIASES = {
    "tool": "tool",
    "skill": "skill",
    "provider": "llm_provider",
    "llm_provider": "llm_provider",
    "channel": "channel_adapter",
    "channel_adapter": "channel_adapter",
    "auth": "auth_provider",
    "auth_provider": "auth_provider",
    "storage": "storage_backend",
    "storage_backend": "storage_backend",
    "workflow": "workflow",
}


@dataclass(slots=True)
class ScaffoldResult:
    kind: str
    name: str
    root: Path
    created_files: list[Path]

    def to_dict(self) -> dict[str, object]:
        return {
            "kind": self.kind,
            "name": self.name,
            "root": str(self.root),
            "created_files": [str(path) for path in self.created_files],
        }


def _slugify(value: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "-", str(value or "").strip()).strip("-").lower()
    if not text:
        raise ValueError("Name cannot be empty")
    return text


def _module_name(value: str) -> str:
    slug = _slugify(value).replace("-", "_")
    if slug and slug[0].isdigit():
        slug = f"ext_{slug}"
    return slug


def _title(value: str) -> str:
    return _slugify(value).replace("-", " ").title()


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8")
    return path


def _manifest(kind: str, name: str, module_name: str, entry_symbol: str, author: str) -> str:
    entrypoint = f"{module_name}:{entry_symbol}" if entry_symbol else ""
    lines = [
        'manifest_version: "1"',
        'contract_version: "1.0"',
        f"name: {name}",
        f"kind: {kind}",
        "version: 0.1.0",
        f"author: {author}",
        f"description: Starter {kind} scaffold for {name}",
        "enabled: true",
        "tags:",
        "  - starter",
        "permissions: []",
        "capabilities: []",
    ]
    if entrypoint:
        lines.append(f"entrypoint: {entrypoint}")
    lines.extend(
        [
            "config_schema:",
            "  type: object",
            "  additionalProperties: false",
            "  properties: {}",
            "metadata: {}",
            "compatibility:",
            '  min_openmiura_version: "1.0.0"',
            "  max_openmiura_version: null",
            "  tested_contract_versions:",
            '    - "1.0"',
            "review:",
            "  reviewers: []",
            "  required_approvals: 1",
        ]
    )
    return "\n".join(lines)


def _package_pyproject(dist_name: str, module_name: str) -> str:
    return f'''[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{dist_name}"
version = "0.1.0"
description = "Extension scaffold for openMiura"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["openmiura"]

[tool.setuptools]
py-modules = ["{module_name}"]
'''


def _readme(kind: str, name: str) -> str:
    title = _title(name)
    return f'''# {title}

Starter scaffold for an openMiura {kind}.

## Files
- `manifest.yaml`: public extension contract
- `pyproject.toml`: packaging metadata
- implementation module
- `tests/test_smoke.py`: local smoke test
- `CHANGELOG.md`: release notes for the registry flow

## Local checks
```bash
openmiura sdk quickstart --kind {kind}
openmiura sdk validate-manifest manifest.yaml
openmiura sdk test-extension .
openmiura registry publish . --root ./registry --namespace demo
openmiura registry review-start {name} 0.1.0 --root ./registry --namespace demo
openmiura registry approve {name} 0.1.0 --root ./registry --namespace demo
openmiura registry verify {name} 0.1.0 --root ./registry --namespace demo
openmiura registry policy-set demo --root ./registry --allowed-namespace demo --allowed-kind {kind}
openmiura registry install {name} --root ./registry --namespace demo --tenant demo
```
'''


def _changelog(name: str) -> str:
    return f'''# Changelog

## 0.1.0
- Initial release of `{name}`.
- Generated by openMiura scaffolding.
'''


def _tool_module(name: str) -> str:
    class_name = _title(name).replace(" ", "") + "Tool"
    return f'''from __future__ import annotations

from typing import Any

from openmiura.extensions.sdk import ExtensionLifecycleContext, ExtensionManifest, ToolExecutionContext


class {class_name}:
    manifest = ExtensionManifest(
        name="{name}",
        kind="tool",
        version="0.1.0",
        description="Starter tool scaffold for {name}",
        compatibility={{"min_openmiura_version": "1.0.0", "tested_contract_versions": ["1.0"]}},
    )

    def initialize(self, ctx: ExtensionLifecycleContext) -> None:
        self._ctx = ctx

    def execute(self, arguments: dict[str, Any], ctx: ToolExecutionContext) -> Any:
        return {{
            "ok": True,
            "tool": self.manifest.name,
            "agent_name": ctx.agent_name,
            "arguments": dict(arguments),
        }}

    def shutdown(self) -> None:
        self._ctx = None


tool = {class_name}()
'''


def _skill_module(name: str) -> str:
    class_name = _title(name).replace(" ", "") + "Skill"
    return f'''from __future__ import annotations

from typing import Any

from openmiura.extensions.sdk import ExtensionLifecycleContext, ExtensionManifest, SkillExecutionContext


class {class_name}:
    manifest = ExtensionManifest(
        name="{name}",
        kind="skill",
        version="0.1.0",
        description="Starter skill scaffold for {name}",
        compatibility={{"min_openmiura_version": "1.0.0", "tested_contract_versions": ["1.0"]}},
    )

    def initialize(self, ctx: ExtensionLifecycleContext) -> None:
        self._ctx = ctx

    def extend_agent_config(self, agent_cfg: dict[str, Any], ctx: SkillExecutionContext) -> dict[str, Any]:
        updated = dict(agent_cfg)
        skills = list(updated.get("skills") or [])
        if self.manifest.name not in skills:
            skills.append(self.manifest.name)
        updated["skills"] = skills
        updated.setdefault("metadata", {{}})
        updated["metadata"]["extended_by"] = self.manifest.name
        return updated

    def shutdown(self) -> None:
        self._ctx = None


skill = {class_name}()
'''


def _provider_module(name: str) -> str:
    class_name = _title(name).replace(" ", "") + "Provider"
    return f'''from __future__ import annotations

from typing import Any

from openmiura.extensions.sdk import ExtensionLifecycleContext, ExtensionManifest, ProviderExecutionContext


class {class_name}:
    manifest = ExtensionManifest(
        name="{name}",
        kind="llm_provider",
        version="0.1.0",
        description="Starter provider scaffold for {name}",
        compatibility={{"min_openmiura_version": "1.0.0", "tested_contract_versions": ["1.0"]}},
    )

    def initialize(self, ctx: ExtensionLifecycleContext) -> None:
        self._ctx = ctx

    def complete(self, prompt: str, ctx: ProviderExecutionContext, **kwargs: Any) -> Any:
        return {{
            "text": f"[{name}] {{prompt}}",
            "model": ctx.model,
            "metadata": dict(kwargs),
        }}

    def shutdown(self) -> None:
        self._ctx = None


provider = {class_name}()
'''


def _channel_module(name: str) -> str:
    class_name = _title(name).replace(" ", "") + "Channel"
    return f'''from __future__ import annotations

from typing import Any

from openmiura.extensions.sdk import ChannelAdapterContext, ChannelMessage, ExtensionLifecycleContext, ExtensionManifest


class {class_name}:
    manifest = ExtensionManifest(
        name="{name}",
        kind="channel_adapter",
        version="0.1.0",
        description="Starter channel adapter scaffold for {name}",
        compatibility={{"min_openmiura_version": "1.0.0", "tested_contract_versions": ["1.0"]}},
    )

    def initialize(self, ctx: ExtensionLifecycleContext) -> None:
        self._ctx = ctx

    def normalize_inbound(self, payload: Any, ctx: ChannelAdapterContext) -> ChannelMessage:
        text = payload.get("text", "") if isinstance(payload, dict) else str(payload)
        channel_user_id = payload.get("user_id", "demo-user") if isinstance(payload, dict) else "demo-user"
        return ChannelMessage(channel=self.manifest.name, channel_user_id=channel_user_id, text=text)

    def format_outbound(self, response: Any, ctx: ChannelAdapterContext) -> Any:
        return {{"channel": self.manifest.name, "response": response}}

    def shutdown(self) -> None:
        self._ctx = None


channel = {class_name}()
'''


def _auth_module(name: str) -> str:
    class_name = _title(name).replace(" ", "") + "AuthProvider"
    return f'''from __future__ import annotations

from typing import Any

from openmiura.extensions.sdk import AuthRequestContext, ExtensionLifecycleContext, ExtensionManifest


class {class_name}:
    manifest = ExtensionManifest(
        name="{name}",
        kind="auth_provider",
        version="0.1.0",
        description="Starter auth provider scaffold for {name}",
        compatibility={{"min_openmiura_version": "1.0.0", "tested_contract_versions": ["1.0"]}},
    )

    def initialize(self, ctx: ExtensionLifecycleContext) -> None:
        self._ctx = ctx

    def authenticate(self, credentials: dict[str, Any], ctx: AuthRequestContext) -> dict[str, Any]:
        token = str(credentials.get("token") or "")
        return {{
            "ok": True,
            "provider": self.manifest.name,
            "channel": ctx.channel,
            "subject": credentials.get("subject") or "demo-user",
            "token_present": bool(token),
        }}

    def shutdown(self) -> None:
        self._ctx = None


auth_provider = {class_name}()
'''


def _storage_module(name: str) -> str:
    class_name = _title(name).replace(" ", "") + "StorageBackend"
    return f'''from __future__ import annotations

from typing import Any

from openmiura.extensions.sdk import ExtensionLifecycleContext, ExtensionManifest, StorageContext


class {class_name}:
    manifest = ExtensionManifest(
        name="{name}",
        kind="storage_backend",
        version="0.1.0",
        description="Starter storage backend scaffold for {name}",
        compatibility={{"min_openmiura_version": "1.0.0", "tested_contract_versions": ["1.0"]}},
    )

    def initialize(self, ctx: ExtensionLifecycleContext) -> None:
        self._ctx = ctx
        self._store: dict[str, Any] = {{}}

    def _scoped_key(self, key: str, ctx: StorageContext) -> str:
        tenant = ctx.tenant_id or "global"
        workspace = ctx.workspace_id or "default"
        environment = ctx.environment or "default"
        return f"{{tenant}}:{{workspace}}:{{environment}}:{{key}}"

    def get(self, key: str, ctx: StorageContext) -> Any:
        return self._store.get(self._scoped_key(key, ctx))

    def put(self, key: str, value: Any, ctx: StorageContext) -> None:
        self._store[self._scoped_key(key, ctx)] = value

    def delete(self, key: str, ctx: StorageContext) -> None:
        self._store.pop(self._scoped_key(key, ctx), None)

    def shutdown(self) -> None:
        self._ctx = None
        self._store = {{}}


storage_backend = {class_name}()
'''


def _smoke_test(kind: str) -> str:
    return f'''from __future__ import annotations

from pathlib import Path

from openmiura.extensions.sdk.harness import ExtensionHarness



def test_extension_smoke() -> None:
    report = ExtensionHarness().run(Path(__file__).resolve().parents[1])
    assert report.ok is True
    assert report.manifest is not None
    assert report.manifest.kind == "{kind}"
    assert report.smoke_result is not None
'''


def _workflow_yaml(name: str) -> str:
    title = _title(name)
    return f'''playbook_id: {name}
version: 0.1.0
name: {title}
description: Starter workflow scaffold generated by openMiura.
category: operations
tags:
  - starter
  - generated
input_schema:
  type: object
  properties:
    subject:
      type: string
      description: Subject or primary business object.
  required: []
definition:
  steps:
    - id: start
      kind: note
      note: "Workflow {name} started for {{{{input.subject}}}}"
    - id: stamp
      kind: tool
      tool_name: time_now
      args: {{}}
    - id: end
      kind: note
      note: "Workflow {name} completed"
'''


def scaffold_project(
    *,
    kind: str,
    name: str,
    output_dir: str | Path = ".",
    author: str = "OpenMiura",
    force: bool = False,
) -> ScaffoldResult:
    resolved_kind = _KIND_ALIASES.get(str(kind).strip().lower())
    if resolved_kind is None:
        supported = ", ".join(sorted(_KIND_ALIASES))
        raise ValueError(f"Unsupported scaffold kind '{kind}'. Supported kinds: {supported}")

    slug = _slugify(name)
    module_name = _module_name(name)
    root = Path(output_dir) / slug
    if root.exists() and any(root.iterdir()) and not force:
        raise FileExistsError(f"Scaffold destination already exists and is not empty: {root}")
    root.mkdir(parents=True, exist_ok=True)

    created: list[Path] = []
    if resolved_kind == "workflow":
        created.append(_write(root / "playbook.yaml", _workflow_yaml(slug)))
        created.append(_write(root / "README.md", _readme("workflow", slug)))
        created.append(_write(root / "CHANGELOG.md", _changelog(slug)))
        return ScaffoldResult(kind="workflow", name=slug, root=root, created_files=created)

    symbol_name = {
        "tool": "tool",
        "skill": "skill",
        "llm_provider": "provider",
        "channel_adapter": "channel",
        "auth_provider": "auth_provider",
        "storage_backend": "storage_backend",
    }[resolved_kind]
    module_body = {
        "tool": _tool_module,
        "skill": _skill_module,
        "llm_provider": _provider_module,
        "channel_adapter": _channel_module,
        "auth_provider": _auth_module,
        "storage_backend": _storage_module,
    }[resolved_kind](slug)

    created.append(_write(root / "manifest.yaml", _manifest(resolved_kind, slug, module_name, symbol_name, author)))
    created.append(_write(root / f"{module_name}.py", module_body))
    created.append(_write(root / "README.md", _readme(resolved_kind, slug)))
    created.append(_write(root / "CHANGELOG.md", _changelog(slug)))
    created.append(_write(root / "pyproject.toml", _package_pyproject(f"openmiura-{slug}", module_name)))
    created.append(_write(root / "tests" / "test_smoke.py", _smoke_test(resolved_kind)))
    return ScaffoldResult(kind=resolved_kind, name=slug, root=root, created_files=created)


__all__ = ["ScaffoldResult", "scaffold_project"]
