"""Migration batch 001 of 2.

Auto-generated split of openmiura/core/migrations.py.
Imported by openmiura/core/migrations/__init__.py and
concatenated into the public ``MIGRATIONS`` tuple.
"""

from __future__ import annotations

from openmiura.core.migrations._migration import Migration


BATCH_001_MIGRATIONS: tuple[Migration, ...] = (
    Migration(
        1,
        "initial_core",
        (
            """
            CREATE TABLE IF NOT EXISTS sessions (
                session_id  TEXT PRIMARY KEY,
                channel     TEXT NOT NULL,
                user_id     TEXT NOT NULL,
                created_at  REAL NOT NULL,
                updated_at  REAL NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS messages (
                id          INTEGER PRIMARY KEY AUTOINCREMENT,
                ts          REAL NOT NULL,
                session_id  TEXT NOT NULL,
                role        TEXT NOT NULL,
                content     TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id)",
            """
            CREATE TABLE IF NOT EXISTS events (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                ts            REAL NOT NULL,
                direction     TEXT NOT NULL,
                channel       TEXT NOT NULL,
                user_id       TEXT NOT NULL,
                session_id    TEXT NOT NULL,
                payload_json  TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_events_channel_ts ON events(channel, ts DESC)",
            """
            CREATE TABLE IF NOT EXISTS memory_items (
                id                INTEGER PRIMARY KEY AUTOINCREMENT,
                user_key          TEXT NOT NULL,
                kind              TEXT NOT NULL,
                text              TEXT NOT NULL,
                embedding         BLOB NOT NULL,
                meta_json         TEXT NOT NULL,
                created_at        REAL NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_memory_user_created ON memory_items(user_key, created_at)",
            """
            CREATE TABLE IF NOT EXISTS identity_map (
                channel_user_key  TEXT PRIMARY KEY,
                global_user_key   TEXT NOT NULL,
                linked_at         REAL NOT NULL,
                linked_by         TEXT NOT NULL DEFAULT 'system'
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS tool_calls (
                id              INTEGER PRIMARY KEY AUTOINCREMENT,
                ts              REAL NOT NULL,
                session_id      TEXT NOT NULL,
                user_key        TEXT NOT NULL,
                agent_id        TEXT NOT NULL,
                tool_name       TEXT NOT NULL,
                args_json       TEXT NOT NULL,
                ok              INTEGER NOT NULL,
                result_excerpt  TEXT NOT NULL,
                error           TEXT NOT NULL,
                duration_ms     REAL NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS telegram_state (
                bot_key         TEXT PRIMARY KEY,
                last_update_id  INTEGER NOT NULL,
                updated_at      REAL NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS slack_event_dedupe (
                event_id    TEXT PRIMARY KEY,
                ts          REAL NOT NULL,
                team_id     TEXT NOT NULL,
                channel_id  TEXT NOT NULL,
                user_id     TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_slack_event_team ON slack_event_dedupe(team_id)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS sessions (
                session_id  TEXT PRIMARY KEY,
                channel     TEXT NOT NULL,
                user_id     TEXT NOT NULL,
                created_at  DOUBLE PRECISION NOT NULL,
                updated_at  DOUBLE PRECISION NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS messages (
                id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts          DOUBLE PRECISION NOT NULL,
                session_id  TEXT NOT NULL,
                role        TEXT NOT NULL,
                content     TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_messages_session ON messages(session_id)",
            """
            CREATE TABLE IF NOT EXISTS events (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts            DOUBLE PRECISION NOT NULL,
                direction     TEXT NOT NULL,
                channel       TEXT NOT NULL,
                user_id       TEXT NOT NULL,
                session_id    TEXT NOT NULL,
                payload_json  TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_events_channel_ts ON events(channel, ts DESC)",
            """
            CREATE TABLE IF NOT EXISTS memory_items (
                id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_key          TEXT NOT NULL,
                kind              TEXT NOT NULL,
                text              TEXT NOT NULL,
                embedding         BYTEA NOT NULL,
                meta_json         TEXT NOT NULL,
                created_at        DOUBLE PRECISION NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_memory_user_created ON memory_items(user_key, created_at)",
            """
            CREATE TABLE IF NOT EXISTS identity_map (
                channel_user_key  TEXT PRIMARY KEY,
                global_user_key   TEXT NOT NULL,
                linked_at         DOUBLE PRECISION NOT NULL,
                linked_by         TEXT NOT NULL DEFAULT 'system'
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS tool_calls (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ts              DOUBLE PRECISION NOT NULL,
                session_id      TEXT NOT NULL,
                user_key        TEXT NOT NULL,
                agent_id        TEXT NOT NULL,
                tool_name       TEXT NOT NULL,
                args_json       TEXT NOT NULL,
                ok              INTEGER NOT NULL,
                result_excerpt  TEXT NOT NULL,
                error           TEXT NOT NULL,
                duration_ms     DOUBLE PRECISION NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS telegram_state (
                bot_key         TEXT PRIMARY KEY,
                last_update_id  INTEGER NOT NULL,
                updated_at      DOUBLE PRECISION NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS slack_event_dedupe (
                event_id    TEXT PRIMARY KEY,
                ts          DOUBLE PRECISION NOT NULL,
                team_id     TEXT NOT NULL,
                channel_id  TEXT NOT NULL,
                user_id     TEXT NOT NULL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_slack_event_team ON slack_event_dedupe(team_id)",
        ),
        (
            "DROP TABLE IF EXISTS slack_event_dedupe",
            "DROP TABLE IF EXISTS telegram_state",
            "DROP TABLE IF EXISTS tool_calls",
            "DROP TABLE IF EXISTS identity_map",
            "DROP TABLE IF EXISTS memory_items",
            "DROP TABLE IF EXISTS events",
            "DROP TABLE IF EXISTS messages",
            "DROP TABLE IF EXISTS sessions",
        ),
        (
            "DROP TABLE IF EXISTS slack_event_dedupe",
            "DROP TABLE IF EXISTS telegram_state",
            "DROP TABLE IF EXISTS tool_calls",
            "DROP TABLE IF EXISTS identity_map",
            "DROP TABLE IF EXISTS memory_items",
            "DROP TABLE IF EXISTS events",
            "DROP TABLE IF EXISTS messages",
            "DROP TABLE IF EXISTS sessions",
        ),
    ),
    Migration(
        2,
        "memory_tiers",
        (
            "ALTER TABLE memory_items ADD COLUMN tier TEXT NOT NULL DEFAULT 'medium'",
            "ALTER TABLE memory_items ADD COLUMN access_count INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE memory_items ADD COLUMN repeat_count INTEGER NOT NULL DEFAULT 1",
            "ALTER TABLE memory_items ADD COLUMN last_accessed_at REAL",
            "CREATE INDEX IF NOT EXISTS idx_memory_user_tier ON memory_items(user_key, tier, created_at DESC)",
        ),
        (
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'medium'",
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS access_count INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS repeat_count INTEGER NOT NULL DEFAULT 1",
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS last_accessed_at DOUBLE PRECISION",
            "CREATE INDEX IF NOT EXISTS idx_memory_user_tier ON memory_items(user_key, tier, created_at DESC)",
        ),
        (),
        (
            "DROP INDEX IF EXISTS idx_memory_user_tier",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS last_accessed_at",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS repeat_count",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS access_count",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS tier",
        ),
    ),
    Migration(
        3,
        "api_auth",
        (
            """
            CREATE TABLE IF NOT EXISTS api_tokens (
                id            INTEGER PRIMARY KEY AUTOINCREMENT,
                user_key      TEXT NOT NULL,
                label         TEXT NOT NULL,
                token_hash    TEXT NOT NULL UNIQUE,
                token_prefix  TEXT NOT NULL,
                scopes_json   TEXT NOT NULL,
                created_at    REAL NOT NULL,
                expires_at    REAL,
                last_used_at  REAL,
                revoked_at    REAL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_key, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS auth_users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT NOT NULL UNIQUE,
                user_key TEXT NOT NULL UNIQUE,
                password_salt TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'user',
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                last_login_at REAL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_auth_users_role ON auth_users(role, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS auth_sessions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL,
                label TEXT NOT NULL,
                token_hash TEXT NOT NULL UNIQUE,
                token_prefix TEXT NOT NULL,
                created_at REAL NOT NULL,
                expires_at REAL,
                last_used_at REAL,
                revoked_at REAL
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id, created_at DESC)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS api_tokens (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_key      TEXT NOT NULL,
                label         TEXT NOT NULL,
                token_hash    TEXT NOT NULL UNIQUE,
                token_prefix  TEXT NOT NULL,
                scopes_json   TEXT NOT NULL,
                created_at    DOUBLE PRECISION NOT NULL,
                expires_at    DOUBLE PRECISION,
                last_used_at  DOUBLE PRECISION,
                revoked_at    DOUBLE PRECISION
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_api_tokens_user ON api_tokens(user_key, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS auth_users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                user_key TEXT NOT NULL UNIQUE,
                password_salt TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                role TEXT NOT NULL DEFAULT 'user',
                is_active INTEGER NOT NULL DEFAULT 1,
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                last_login_at DOUBLE PRECISION
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_auth_users_role ON auth_users(role, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS auth_sessions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                label TEXT NOT NULL,
                token_hash TEXT NOT NULL UNIQUE,
                token_prefix TEXT NOT NULL,
                created_at DOUBLE PRECISION NOT NULL,
                expires_at DOUBLE PRECISION,
                last_used_at DOUBLE PRECISION,
                revoked_at DOUBLE PRECISION
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON auth_sessions(user_id, created_at DESC)",
        ),
        (
            "DROP TABLE IF EXISTS auth_sessions",
            "DROP TABLE IF EXISTS auth_users",
            "DROP TABLE IF EXISTS api_tokens",
        ),
        (
            "DROP TABLE IF EXISTS auth_sessions",
            "DROP TABLE IF EXISTS auth_users",
            "DROP TABLE IF EXISTS api_tokens",
        ),
    ),
    Migration(
        4,
        "tenancy_foundation",
        (
            """
            CREATE TABLE IF NOT EXISTS tenants (
                tenant_id TEXT PRIMARY KEY,
                display_name TEXT NOT NULL DEFAULT '',
                created_at REAL NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS workspaces (
                tenant_id TEXT NOT NULL,
                workspace_id TEXT NOT NULL,
                display_name TEXT NOT NULL DEFAULT '',
                default_environment TEXT NOT NULL DEFAULT 'prod',
                environments_json TEXT NOT NULL DEFAULT '[]',
                created_at REAL NOT NULL,
                PRIMARY KEY (tenant_id, workspace_id)
            )
            """,
            "ALTER TABLE sessions ADD COLUMN tenant_id TEXT",
            "ALTER TABLE sessions ADD COLUMN workspace_id TEXT",
            "ALTER TABLE sessions ADD COLUMN environment TEXT",
            "ALTER TABLE events ADD COLUMN tenant_id TEXT",
            "ALTER TABLE events ADD COLUMN workspace_id TEXT",
            "ALTER TABLE events ADD COLUMN environment TEXT",
            "ALTER TABLE memory_items ADD COLUMN tenant_id TEXT",
            "ALTER TABLE memory_items ADD COLUMN workspace_id TEXT",
            "ALTER TABLE memory_items ADD COLUMN environment TEXT",
            "ALTER TABLE identity_map ADD COLUMN tenant_id TEXT",
            "ALTER TABLE identity_map ADD COLUMN workspace_id TEXT",
            "ALTER TABLE tool_calls ADD COLUMN tenant_id TEXT",
            "ALTER TABLE tool_calls ADD COLUMN workspace_id TEXT",
            "ALTER TABLE tool_calls ADD COLUMN environment TEXT",
            "ALTER TABLE api_tokens ADD COLUMN tenant_id TEXT",
            "ALTER TABLE api_tokens ADD COLUMN workspace_id TEXT",
            "ALTER TABLE api_tokens ADD COLUMN environment TEXT",
            "ALTER TABLE auth_users ADD COLUMN tenant_id TEXT",
            "ALTER TABLE auth_users ADD COLUMN workspace_id TEXT",
            "ALTER TABLE auth_sessions ADD COLUMN tenant_id TEXT",
            "ALTER TABLE auth_sessions ADD COLUMN workspace_id TEXT",
            "ALTER TABLE auth_sessions ADD COLUMN environment TEXT",
            "CREATE INDEX IF NOT EXISTS idx_sessions_scope ON sessions(tenant_id, workspace_id, environment, updated_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_events_scope ON events(tenant_id, workspace_id, environment, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_memory_scope ON memory_items(tenant_id, workspace_id, environment, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_auth_users_scope ON auth_users(tenant_id, workspace_id, created_at DESC)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS tenants (
                tenant_id TEXT PRIMARY KEY,
                display_name TEXT NOT NULL DEFAULT '',
                created_at DOUBLE PRECISION NOT NULL
            )
            """,
            """
            CREATE TABLE IF NOT EXISTS workspaces (
                tenant_id TEXT NOT NULL,
                workspace_id TEXT NOT NULL,
                display_name TEXT NOT NULL DEFAULT '',
                default_environment TEXT NOT NULL DEFAULT 'prod',
                environments_json TEXT NOT NULL DEFAULT '[]',
                created_at DOUBLE PRECISION NOT NULL,
                PRIMARY KEY (tenant_id, workspace_id)
            )
            """,
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE sessions ADD COLUMN IF NOT EXISTS environment TEXT",
            "ALTER TABLE events ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE events ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE events ADD COLUMN IF NOT EXISTS environment TEXT",
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE memory_items ADD COLUMN IF NOT EXISTS environment TEXT",
            "ALTER TABLE identity_map ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE identity_map ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE tool_calls ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE tool_calls ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE tool_calls ADD COLUMN IF NOT EXISTS environment TEXT",
            "ALTER TABLE api_tokens ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE api_tokens ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE api_tokens ADD COLUMN IF NOT EXISTS environment TEXT",
            "ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE auth_users ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS tenant_id TEXT",
            "ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS workspace_id TEXT",
            "ALTER TABLE auth_sessions ADD COLUMN IF NOT EXISTS environment TEXT",
            "CREATE INDEX IF NOT EXISTS idx_sessions_scope ON sessions(tenant_id, workspace_id, environment, updated_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_events_scope ON events(tenant_id, workspace_id, environment, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_memory_scope ON memory_items(tenant_id, workspace_id, environment, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_auth_users_scope ON auth_users(tenant_id, workspace_id, created_at DESC)",
        ),
        (
            "DROP INDEX IF EXISTS idx_auth_users_scope",
            "DROP INDEX IF EXISTS idx_memory_scope",
            "DROP INDEX IF EXISTS idx_events_scope",
            "DROP INDEX IF EXISTS idx_sessions_scope",
            "DROP TABLE IF EXISTS workspaces",
            "DROP TABLE IF EXISTS tenants",
        ),
        (
            "DROP INDEX IF EXISTS idx_auth_users_scope",
            "DROP INDEX IF EXISTS idx_memory_scope",
            "DROP INDEX IF EXISTS idx_events_scope",
            "DROP INDEX IF EXISTS idx_sessions_scope",
            "ALTER TABLE auth_sessions DROP COLUMN IF EXISTS environment",
            "ALTER TABLE auth_sessions DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE auth_sessions DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE auth_users DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE auth_users DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE api_tokens DROP COLUMN IF EXISTS environment",
            "ALTER TABLE api_tokens DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE api_tokens DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE tool_calls DROP COLUMN IF EXISTS environment",
            "ALTER TABLE tool_calls DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE tool_calls DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE identity_map DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE identity_map DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS environment",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE memory_items DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE events DROP COLUMN IF EXISTS environment",
            "ALTER TABLE events DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE events DROP COLUMN IF EXISTS tenant_id",
            "ALTER TABLE sessions DROP COLUMN IF EXISTS environment",
            "ALTER TABLE sessions DROP COLUMN IF EXISTS workspace_id",
            "ALTER TABLE sessions DROP COLUMN IF EXISTS tenant_id",
            "DROP TABLE IF EXISTS workspaces",
            "DROP TABLE IF EXISTS tenants",
        ),
    ),
    Migration(
        5,
        "workflow_engine",
        (
            """
            CREATE TABLE IF NOT EXISTS workflows (
                workflow_id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                status TEXT NOT NULL,
                created_by TEXT NOT NULL,
                definition_json TEXT NOT NULL,
                input_json TEXT NOT NULL,
                context_json TEXT NOT NULL,
                current_step_index INTEGER NOT NULL DEFAULT 0,
                current_step_id TEXT,
                waiting_for_approval INTEGER NOT NULL DEFAULT 0,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                started_at REAL,
                finished_at REAL,
                error TEXT NOT NULL DEFAULT '',
                source_job_id TEXT,
                playbook_id TEXT,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_workflows_scope ON workflows(tenant_id, workspace_id, environment, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_workflows_status ON workflows(status, updated_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS approvals (
                approval_id TEXT PRIMARY KEY,
                workflow_id TEXT NOT NULL,
                step_id TEXT NOT NULL,
                requested_role TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                status TEXT NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                payload_json TEXT NOT NULL,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                expires_at REAL,
                decided_at REAL,
                decided_by TEXT,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_approvals_status_scope ON approvals(status, tenant_id, workspace_id, environment, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS job_schedules (
                job_id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                enabled INTEGER NOT NULL DEFAULT 1,
                interval_s INTEGER,
                next_run_at REAL,
                last_run_at REAL,
                workflow_definition_json TEXT NOT NULL,
                input_json TEXT NOT NULL,
                created_by TEXT NOT NULL,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                playbook_id TEXT,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_job_schedules_scope ON job_schedules(enabled, tenant_id, workspace_id, environment, next_run_at)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS workflows (
                workflow_id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                status TEXT NOT NULL,
                created_by TEXT NOT NULL,
                definition_json TEXT NOT NULL,
                input_json TEXT NOT NULL,
                context_json TEXT NOT NULL,
                current_step_index INTEGER NOT NULL DEFAULT 0,
                current_step_id TEXT,
                waiting_for_approval INTEGER NOT NULL DEFAULT 0,
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                started_at DOUBLE PRECISION,
                finished_at DOUBLE PRECISION,
                error TEXT NOT NULL DEFAULT '',
                source_job_id TEXT,
                playbook_id TEXT,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_workflows_scope ON workflows(tenant_id, workspace_id, environment, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_workflows_status ON workflows(status, updated_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS approvals (
                approval_id TEXT PRIMARY KEY,
                workflow_id TEXT NOT NULL,
                step_id TEXT NOT NULL,
                requested_role TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                status TEXT NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                payload_json TEXT NOT NULL,
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                expires_at DOUBLE PRECISION,
                decided_at DOUBLE PRECISION,
                decided_by TEXT,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_approvals_status_scope ON approvals(status, tenant_id, workspace_id, environment, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS job_schedules (
                job_id TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                enabled INTEGER NOT NULL DEFAULT 1,
                interval_s INTEGER,
                next_run_at DOUBLE PRECISION,
                last_run_at DOUBLE PRECISION,
                workflow_definition_json TEXT NOT NULL,
                input_json TEXT NOT NULL,
                created_by TEXT NOT NULL,
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                playbook_id TEXT,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_job_schedules_scope ON job_schedules(enabled, tenant_id, workspace_id, environment, next_run_at)",
        ),
        (
            "DROP TABLE IF EXISTS job_schedules",
            "DROP TABLE IF EXISTS approvals",
            "DROP TABLE IF EXISTS workflows",
        ),
        (
            "DROP TABLE IF EXISTS job_schedules",
            "DROP TABLE IF EXISTS approvals",
            "DROP TABLE IF EXISTS workflows",
        ),
    ),
    Migration(
        6,
        "workflow_runtime_scheduler",
        (
            "ALTER TABLE approvals ADD COLUMN assigned_to TEXT",
            "ALTER TABLE approvals ADD COLUMN claimed_at REAL",
            "ALTER TABLE job_schedules ADD COLUMN schedule_kind TEXT NOT NULL DEFAULT 'interval'",
            "ALTER TABLE job_schedules ADD COLUMN schedule_expr TEXT",
            "ALTER TABLE job_schedules ADD COLUMN timezone TEXT NOT NULL DEFAULT 'UTC'",
            "ALTER TABLE job_schedules ADD COLUMN not_before REAL",
            "ALTER TABLE job_schedules ADD COLUMN not_after REAL",
            "ALTER TABLE job_schedules ADD COLUMN max_runs INTEGER",
            "ALTER TABLE job_schedules ADD COLUMN run_count INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE job_schedules ADD COLUMN last_error TEXT NOT NULL DEFAULT ''",
        ),
        (
            "ALTER TABLE approvals ADD COLUMN IF NOT EXISTS assigned_to TEXT",
            "ALTER TABLE approvals ADD COLUMN IF NOT EXISTS claimed_at DOUBLE PRECISION",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS schedule_kind TEXT NOT NULL DEFAULT 'interval'",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS schedule_expr TEXT",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'UTC'",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS not_before DOUBLE PRECISION",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS not_after DOUBLE PRECISION",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS max_runs INTEGER",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS run_count INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE job_schedules ADD COLUMN IF NOT EXISTS last_error TEXT NOT NULL DEFAULT ''",
        ),
        (),
        (
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS last_error",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS run_count",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS max_runs",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS not_after",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS not_before",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS timezone",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS schedule_expr",
            "ALTER TABLE job_schedules DROP COLUMN IF EXISTS schedule_kind",
            "ALTER TABLE approvals DROP COLUMN IF EXISTS claimed_at",
            "ALTER TABLE approvals DROP COLUMN IF EXISTS assigned_to",
        ),
    ),
    Migration(
        7,
        "evaluation_harness",
        (
            """
            CREATE TABLE IF NOT EXISTS evaluation_runs (
                run_id TEXT PRIMARY KEY,
                suite_name TEXT NOT NULL,
                status TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                provider TEXT NOT NULL DEFAULT '',
                model TEXT NOT NULL DEFAULT '',
                agent_name TEXT NOT NULL DEFAULT '',
                started_at REAL NOT NULL,
                completed_at REAL,
                total_cases INTEGER NOT NULL DEFAULT 0,
                passed_cases INTEGER NOT NULL DEFAULT 0,
                failed_cases INTEGER NOT NULL DEFAULT 0,
                average_latency_ms REAL NOT NULL DEFAULT 0,
                total_cost REAL NOT NULL DEFAULT 0,
                scorecard_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_evaluation_runs_scope ON evaluation_runs(tenant_id, workspace_id, environment, started_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_evaluation_runs_suite ON evaluation_runs(suite_name, started_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS evaluation_case_results (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                run_id TEXT NOT NULL,
                case_id TEXT NOT NULL,
                case_name TEXT NOT NULL,
                status TEXT NOT NULL,
                passed INTEGER NOT NULL,
                score REAL NOT NULL DEFAULT 0,
                latency_ms REAL NOT NULL DEFAULT 0,
                cost REAL NOT NULL DEFAULT 0,
                assertions_total INTEGER NOT NULL DEFAULT 0,
                assertions_passed INTEGER NOT NULL DEFAULT 0,
                details_json TEXT NOT NULL DEFAULT '{}',
                observed_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_evaluation_results_run ON evaluation_case_results(run_id, id)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS evaluation_runs (
                run_id TEXT PRIMARY KEY,
                suite_name TEXT NOT NULL,
                status TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                provider TEXT NOT NULL DEFAULT '',
                model TEXT NOT NULL DEFAULT '',
                agent_name TEXT NOT NULL DEFAULT '',
                started_at DOUBLE PRECISION NOT NULL,
                completed_at DOUBLE PRECISION,
                total_cases INTEGER NOT NULL DEFAULT 0,
                passed_cases INTEGER NOT NULL DEFAULT 0,
                failed_cases INTEGER NOT NULL DEFAULT 0,
                average_latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
                total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
                scorecard_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_evaluation_runs_scope ON evaluation_runs(tenant_id, workspace_id, environment, started_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_evaluation_runs_suite ON evaluation_runs(suite_name, started_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS evaluation_case_results (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id TEXT NOT NULL,
                case_id TEXT NOT NULL,
                case_name TEXT NOT NULL,
                status TEXT NOT NULL,
                passed INTEGER NOT NULL,
                score DOUBLE PRECISION NOT NULL DEFAULT 0,
                latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
                cost DOUBLE PRECISION NOT NULL DEFAULT 0,
                assertions_total INTEGER NOT NULL DEFAULT 0,
                assertions_passed INTEGER NOT NULL DEFAULT 0,
                details_json TEXT NOT NULL DEFAULT '{}',
                observed_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_evaluation_results_run ON evaluation_case_results(run_id, id)",
        ),
        (
            "DROP TABLE IF EXISTS evaluation_case_results",
            "DROP TABLE IF EXISTS evaluation_runs",
        ),
        (
            "DROP TABLE IF EXISTS evaluation_case_results",
            "DROP TABLE IF EXISTS evaluation_runs",
        ),
    ),
    Migration(
        8,
        "decision_trace_inspector",
        (
            """
            CREATE TABLE IF NOT EXISTS decision_traces (
                trace_id TEXT PRIMARY KEY,
                ts REAL NOT NULL,
                session_id TEXT NOT NULL,
                user_key TEXT NOT NULL DEFAULT '',
                channel TEXT NOT NULL DEFAULT '',
                agent_id TEXT NOT NULL DEFAULT '',
                request_text TEXT NOT NULL DEFAULT '',
                response_text TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT 'completed',
                provider TEXT NOT NULL DEFAULT '',
                model TEXT NOT NULL DEFAULT '',
                latency_ms REAL NOT NULL DEFAULT 0,
                estimated_cost REAL NOT NULL DEFAULT 0,
                llm_calls INTEGER NOT NULL DEFAULT 0,
                input_tokens INTEGER NOT NULL DEFAULT 0,
                output_tokens INTEGER NOT NULL DEFAULT 0,
                total_tokens INTEGER NOT NULL DEFAULT 0,
                context_json TEXT NOT NULL DEFAULT '{}',
                memory_json TEXT NOT NULL DEFAULT '{}',
                tools_considered_json TEXT NOT NULL DEFAULT '[]',
                tools_used_json TEXT NOT NULL DEFAULT '[]',
                policies_json TEXT NOT NULL DEFAULT '[]',
                decisions_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_decision_traces_scope ON decision_traces(tenant_id, workspace_id, environment, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_decision_traces_session ON decision_traces(session_id, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_decision_traces_agent ON decision_traces(agent_id, ts DESC)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS decision_traces (
                trace_id TEXT PRIMARY KEY,
                ts DOUBLE PRECISION NOT NULL,
                session_id TEXT NOT NULL,
                user_key TEXT NOT NULL DEFAULT '',
                channel TEXT NOT NULL DEFAULT '',
                agent_id TEXT NOT NULL DEFAULT '',
                request_text TEXT NOT NULL DEFAULT '',
                response_text TEXT NOT NULL DEFAULT '',
                status TEXT NOT NULL DEFAULT 'completed',
                provider TEXT NOT NULL DEFAULT '',
                model TEXT NOT NULL DEFAULT '',
                latency_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
                estimated_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
                llm_calls INTEGER NOT NULL DEFAULT 0,
                input_tokens INTEGER NOT NULL DEFAULT 0,
                output_tokens INTEGER NOT NULL DEFAULT 0,
                total_tokens INTEGER NOT NULL DEFAULT 0,
                context_json TEXT NOT NULL DEFAULT '{}',
                memory_json TEXT NOT NULL DEFAULT '{}',
                tools_considered_json TEXT NOT NULL DEFAULT '[]',
                tools_used_json TEXT NOT NULL DEFAULT '[]',
                policies_json TEXT NOT NULL DEFAULT '[]',
                decisions_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_decision_traces_scope ON decision_traces(tenant_id, workspace_id, environment, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_decision_traces_session ON decision_traces(session_id, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_decision_traces_agent ON decision_traces(agent_id, ts DESC)",
        ),
        (
            "DROP TABLE IF EXISTS decision_traces",
        ),
        (
            "DROP TABLE IF EXISTS decision_traces",
        ),
    ),
    Migration(
        9,
        "release_governance_base",
        (
            """
            CREATE TABLE IF NOT EXISTS release_bundles (
                release_id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,
                name TEXT NOT NULL,
                version TEXT NOT NULL,
                status TEXT NOT NULL,
                environment TEXT,
                created_by TEXT NOT NULL,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                submitted_at REAL,
                approved_at REAL,
                promoted_at REAL,
                rejected_at REAL,
                notes TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_bundles_scope ON release_bundles(tenant_id, workspace_id, environment, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_release_bundles_name ON release_bundles(kind, name, version)",
            "CREATE INDEX IF NOT EXISTS idx_release_bundles_status ON release_bundles(status, updated_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_bundle_items (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                release_id TEXT NOT NULL,
                item_kind TEXT NOT NULL,
                item_key TEXT NOT NULL,
                item_version TEXT NOT NULL DEFAULT '',
                payload_json TEXT NOT NULL DEFAULT '{}'
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_bundle_items_release ON release_bundle_items(release_id, id)",
            """
            CREATE TABLE IF NOT EXISTS release_promotions (
                promotion_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                from_environment TEXT,
                to_environment TEXT NOT NULL,
                status TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                requested_at REAL NOT NULL,
                approved_by TEXT NOT NULL DEFAULT '',
                approved_at REAL,
                completed_at REAL,
                gate_result_json TEXT NOT NULL DEFAULT '{}',
                summary_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_promotions_release ON release_promotions(release_id, requested_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_release_promotions_scope ON release_promotions(tenant_id, workspace_id, to_environment, requested_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_approvals (
                approval_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                actor TEXT NOT NULL,
                action TEXT NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                created_at REAL NOT NULL,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_approvals_release ON release_approvals(release_id, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_rollbacks (
                rollback_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                rolled_back_release_id TEXT,
                environment TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                created_at REAL NOT NULL,
                snapshot_id TEXT,
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_rollbacks_release ON release_rollbacks(release_id, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS environment_snapshots (
                snapshot_id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,
                name TEXT NOT NULL,
                environment TEXT NOT NULL,
                active_release_id TEXT,
                previous_release_id TEXT,
                ts REAL NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                tenant_id TEXT,
                workspace_id TEXT,
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_environment_snapshots_scope ON environment_snapshots(tenant_id, workspace_id, environment, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_environment_snapshots_release ON environment_snapshots(active_release_id, previous_release_id)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS release_bundles (
                release_id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,
                name TEXT NOT NULL,
                version TEXT NOT NULL,
                status TEXT NOT NULL,
                environment TEXT,
                created_by TEXT NOT NULL,
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                submitted_at DOUBLE PRECISION,
                approved_at DOUBLE PRECISION,
                promoted_at DOUBLE PRECISION,
                rejected_at DOUBLE PRECISION,
                notes TEXT NOT NULL DEFAULT '',
                metadata_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_bundles_scope ON release_bundles(tenant_id, workspace_id, environment, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_release_bundles_name ON release_bundles(kind, name, version)",
            "CREATE INDEX IF NOT EXISTS idx_release_bundles_status ON release_bundles(status, updated_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_bundle_items (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                release_id TEXT NOT NULL,
                item_kind TEXT NOT NULL,
                item_key TEXT NOT NULL,
                item_version TEXT NOT NULL DEFAULT '',
                payload_json TEXT NOT NULL DEFAULT '{}'
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_bundle_items_release ON release_bundle_items(release_id, id)",
            """
            CREATE TABLE IF NOT EXISTS release_promotions (
                promotion_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                from_environment TEXT,
                to_environment TEXT NOT NULL,
                status TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                requested_at DOUBLE PRECISION NOT NULL,
                approved_by TEXT NOT NULL DEFAULT '',
                approved_at DOUBLE PRECISION,
                completed_at DOUBLE PRECISION,
                gate_result_json TEXT NOT NULL DEFAULT '{}',
                summary_json TEXT NOT NULL DEFAULT '{}',
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_promotions_release ON release_promotions(release_id, requested_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_release_promotions_scope ON release_promotions(tenant_id, workspace_id, to_environment, requested_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_approvals (
                approval_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                actor TEXT NOT NULL,
                action TEXT NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                created_at DOUBLE PRECISION NOT NULL,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_approvals_release ON release_approvals(release_id, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_rollbacks (
                rollback_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                rolled_back_release_id TEXT,
                environment TEXT NOT NULL,
                requested_by TEXT NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                created_at DOUBLE PRECISION NOT NULL,
                snapshot_id TEXT,
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_rollbacks_release ON release_rollbacks(release_id, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS environment_snapshots (
                snapshot_id TEXT PRIMARY KEY,
                kind TEXT NOT NULL,
                name TEXT NOT NULL,
                environment TEXT NOT NULL,
                active_release_id TEXT,
                previous_release_id TEXT,
                ts DOUBLE PRECISION NOT NULL,
                reason TEXT NOT NULL DEFAULT '',
                tenant_id TEXT,
                workspace_id TEXT,
                metadata_json TEXT NOT NULL DEFAULT '{}'
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_environment_snapshots_scope ON environment_snapshots(tenant_id, workspace_id, environment, ts DESC)",
            "CREATE INDEX IF NOT EXISTS idx_environment_snapshots_release ON environment_snapshots(active_release_id, previous_release_id)",
        ),
        (
            "DROP TABLE IF EXISTS environment_snapshots",
            "DROP TABLE IF EXISTS release_rollbacks",
            "DROP TABLE IF EXISTS release_approvals",
            "DROP TABLE IF EXISTS release_promotions",
            "DROP TABLE IF EXISTS release_bundle_items",
            "DROP TABLE IF EXISTS release_bundles",
        ),
        (
            "DROP TABLE IF EXISTS environment_snapshots",
            "DROP TABLE IF EXISTS release_rollbacks",
            "DROP TABLE IF EXISTS release_approvals",
            "DROP TABLE IF EXISTS release_promotions",
            "DROP TABLE IF EXISTS release_bundle_items",
            "DROP TABLE IF EXISTS release_bundles",
        ),
    ),
    Migration(
        10,
        "release_canary_governance",
        (
            """
            CREATE TABLE IF NOT EXISTS release_canaries (
                canary_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                target_environment TEXT NOT NULL,
                strategy TEXT NOT NULL DEFAULT 'percentage',
                traffic_percent REAL NOT NULL DEFAULT 0,
                step_percent REAL NOT NULL DEFAULT 0,
                bake_minutes INTEGER NOT NULL DEFAULT 0,
                status TEXT NOT NULL DEFAULT 'draft',
                metric_guardrails_json TEXT NOT NULL DEFAULT '{}',
                analysis_summary_json TEXT NOT NULL DEFAULT '{}',
                created_by TEXT NOT NULL,
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                activated_at REAL,
                completed_at REAL,
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_release_canaries_release ON release_canaries(release_id)",
            "CREATE INDEX IF NOT EXISTS idx_release_canaries_scope ON release_canaries(tenant_id, workspace_id, target_environment, updated_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_gate_runs (
                gate_run_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                gate_name TEXT NOT NULL,
                status TEXT NOT NULL,
                score REAL,
                threshold REAL,
                details_json TEXT NOT NULL DEFAULT '{}',
                executed_by TEXT NOT NULL DEFAULT '',
                created_at REAL NOT NULL,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_gate_runs_release ON release_gate_runs(release_id, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_release_gate_runs_scope ON release_gate_runs(tenant_id, workspace_id, environment, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_change_reports (
                report_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                risk_level TEXT NOT NULL DEFAULT 'unknown',
                summary_json TEXT NOT NULL DEFAULT '{}',
                diff_json TEXT NOT NULL DEFAULT '{}',
                created_by TEXT NOT NULL DEFAULT '',
                created_at REAL NOT NULL,
                updated_at REAL NOT NULL,
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_release_change_reports_release ON release_change_reports(release_id)",
            "CREATE INDEX IF NOT EXISTS idx_release_change_reports_scope ON release_change_reports(tenant_id, workspace_id, updated_at DESC)",
        ),
        (
            """
            CREATE TABLE IF NOT EXISTS release_canaries (
                canary_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                target_environment TEXT NOT NULL,
                strategy TEXT NOT NULL DEFAULT 'percentage',
                traffic_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
                step_percent DOUBLE PRECISION NOT NULL DEFAULT 0,
                bake_minutes INTEGER NOT NULL DEFAULT 0,
                status TEXT NOT NULL DEFAULT 'draft',
                metric_guardrails_json TEXT NOT NULL DEFAULT '{}',
                analysis_summary_json TEXT NOT NULL DEFAULT '{}',
                created_by TEXT NOT NULL,
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                activated_at DOUBLE PRECISION,
                completed_at DOUBLE PRECISION,
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_release_canaries_release ON release_canaries(release_id)",
            "CREATE INDEX IF NOT EXISTS idx_release_canaries_scope ON release_canaries(tenant_id, workspace_id, target_environment, updated_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_gate_runs (
                gate_run_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                gate_name TEXT NOT NULL,
                status TEXT NOT NULL,
                score DOUBLE PRECISION,
                threshold DOUBLE PRECISION,
                details_json TEXT NOT NULL DEFAULT '{}',
                executed_by TEXT NOT NULL DEFAULT '',
                created_at DOUBLE PRECISION NOT NULL,
                tenant_id TEXT,
                workspace_id TEXT,
                environment TEXT
            )
            """,
            "CREATE INDEX IF NOT EXISTS idx_release_gate_runs_release ON release_gate_runs(release_id, created_at DESC)",
            "CREATE INDEX IF NOT EXISTS idx_release_gate_runs_scope ON release_gate_runs(tenant_id, workspace_id, environment, created_at DESC)",
            """
            CREATE TABLE IF NOT EXISTS release_change_reports (
                report_id TEXT PRIMARY KEY,
                release_id TEXT NOT NULL,
                risk_level TEXT NOT NULL DEFAULT 'unknown',
                summary_json TEXT NOT NULL DEFAULT '{}',
                diff_json TEXT NOT NULL DEFAULT '{}',
                created_by TEXT NOT NULL DEFAULT '',
                created_at DOUBLE PRECISION NOT NULL,
                updated_at DOUBLE PRECISION NOT NULL,
                tenant_id TEXT,
                workspace_id TEXT
            )
            """,
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_release_change_reports_release ON release_change_reports(release_id)",
            "CREATE INDEX IF NOT EXISTS idx_release_change_reports_scope ON release_change_reports(tenant_id, workspace_id, updated_at DESC)",
        ),
        (
            "DROP TABLE IF EXISTS release_change_reports",
            "DROP TABLE IF EXISTS release_gate_runs",
            "DROP TABLE IF EXISTS release_canaries",
        ),
        (
            "DROP TABLE IF EXISTS release_change_reports",
            "DROP TABLE IF EXISTS release_gate_runs",
            "DROP TABLE IF EXISTS release_canaries",
        ),
    ),
)
